# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Technical Document Center
author: YB
logo: ./img/tdc_logo_5.jpg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto
  timeout: 120
  exclude_patterns:
    - '_*.md'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/yoblee/tdc  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

#######################################################################################
# Parse and render settings
parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    # - amsmath
    - colon_fence
    - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist
  myst_url_schemes: [mailto, http, https] # URI schemes that will be recognised as external URLs in Markdown links
  myst_dmath_double_inline: true  # Allow display math ($$) within an inline context

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_multitoc_numbering: false

sphinx:
  extra_extensions:
    - myst_parser
    - myst_nb
    - sphinxcontrib.mermaid
    - sphinxawesome_theme.docsearch
    - sphinxawesome.highlighting
    
sphinx:
  config:
    # html_css_files: custom.css
#     sphinxemoji_style: twemoji
    # html_theme: sphinx_book_theme
    # html_theme: sphinx_rtd_theme
    # html_theme: pydata_sphinx_theme
    # html_theme: press # error
    # html_theme: furo
    # html_theme: piccolo_theme
    # html_theme: sphinx_material
    # html_theme: sphinxawesome_theme
    # html_theme: sphinx_typo3_theme
    # html_theme: bulma_sphinx_theme
    html_theme: shibuya
    # html_theme_options: 
    #   have_top_navbar: false
    # html_css_files:
    #   - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/fontawesome.css
      # - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/fontawesome.min.css
      # - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/solid.min.css
      # - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/brands.min.css
    # html_js_files: [ ['https://plausible.io/js/script.js', {'defer': 'defer', 'data-domain': 'yourdomain.com'}] ]

    html_logo: _static/tdc_logo_7.png
    html_theme_options: 
      "nav_links": [
          {
              "title": "Documentation",
              "url": "dc/jupyter-book",
              "children": [
                  {
                      "title": "jupyter book",
                      "url": "dc/jupyter-book",
                  },
                  {
                      "title": "sphinx",
                      "url": "dc/sphinx",
                  },
                  {
                      "title": "jupytext",
                      "url": "dc/jupytext_01",
                  },
                  {
                      "title": "markup",
                      "url": "dc/markup",
                  },
              ]
          },
          {
              "title": "Python",
              "url": "py/pandas",
              "children": [
                  {
                      "title": "pandas",
                      "url": "py/pandas",
                  },
                  {
                      "title": "pdm",
                      "url": "py/pdm",
                  },
              ]
          },
          {
              "title": "Data Visualization",
              "url": "dv/seaborn",
              "children": [
                  {
                      "title": "seaborn",
                      "url": "dv/seaborn",
                  },
                  {
                      "title": "bokeh",
                      "url": "dv/bokeh",
                  },
              ]
          },
      ]
      "github_url": "https://github.com/gritism/tdc"

    html_js_files:
      - 'js/mermaid.js'
